# Generated by Django 5.1.7 on 2025-03-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployeditem',
            name='creator_id',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='deployeditem',
            name='updator_id',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
