# Generated by Django 5.1.7 on 2025-03-24 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=250)),
                ('client_phone', models.CharField(max_length=50)),
                ('client_package', models.CharField(max_length=250)),
                ('client_location', models.CharField(max_length=250)),
                ('longitude', models.CharField(max_length=150)),
                ('latitude', models.CharField(max_length=150)),
                ('referer_name', models.CharField(max_length=250)),
                ('referer_phone', models.CharField(max_length=50)),
                ('mpesa_message', models.TextField()),
                ('awarded', models.BooleanField(default=False)),
                ('creator_id', models.IntegerField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='references', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
