# Generated by Django 5.1.7 on 2025-03-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchased', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseditem',
            name='seller_contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchaseditem',
            name='seller_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseditem',
            name='seller_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseditem',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
